<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\IndustrialAutomationStudio.Modules.Communication\IndustrialAutomationStudio.Modules.Communication.csproj" />
    <ProjectReference Include="..\IndustrialAutomationStudio.Modules.Diagnostics\IndustrialAutomationStudio.Modules.Diagnostics.csproj" />
    <ProjectReference Include="..\IndustrialAutomationStudio.Modules.Motion\IndustrialAutomationStudio.Modules.Motion.csproj" />
    <ProjectReference Include="..\IndustrialAutomationStudio.Modules.Settings\IndustrialAutomationStudio.Modules.Settings.csproj" />
    <ProjectReference Include="..\IndustrialAutomationStudio.Modules.Workbench\IndustrialAutomationStudio.Modules.Workbench.csproj" />
    <ProjectReference Include="..\IndustrialAutomationStudio.Modules.Workflow\IndustrialAutomationStudio.Modules.Workflow.csproj" />
    <ProjectReference Include="..\IndustrialAutomationStudio.Shell.Contracts\IndustrialAutomationStudio.Shell.Contracts.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Prism.DryIoc" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="..\Assembly\ecat_motion.dll" Link="ecat_motion.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
    </Content>
  </ItemGroup>

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

</Project>
